aqui

In [1]:
#Comenzamos accediendo al contenido de drive y leyendo el archivo
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import os
import pandas as pd
import numpy as np

## Homologar columnas

In [ ]:
df_1=pd.read_csv('/content/drive/MyDrive/HackODS/elias/hackathon/datas/01_registro_alumnado_personal/data/BASICA_2021-2022.csv', encoding='latin1')
df_1[['entidad','n_entidad','nivel', 'periodo','insc_t','hom_t','muj_t','egre_hom','egre_muj','egre_tot','docente_h','docente_m','tot_doc']].head()

,entidad,n_entidad,nivel,periodo,insc_t,hom_t,muj_t,egre_hom,egre_muj,egre_tot,docente_h,docente_m,tot_doc
0,1,AGUASCALIENTES,PREESCOLAR,I2122,93,47,46,0,0,0,0,4,4
1,1,AGUASCALIENTES,PREESCOLAR,I2122,186,97,89,0,0,0,0,7,7
2,1,AGUASCALIENTES,SECUNDARIA,I2122,670,313,357,102,104,206,12,11,23
3,1,AGUASCALIENTES,PREESCOLAR,I2122,58,34,24,0,0,0,0,2,2
4,1,AGUASCALIENTES,PREESCOLAR,I2122,105,53,52,0,0,0,0,4,4

In [ ]:
df_1=pd.read_csv('/content/drive/MyDrive/HackODS/elias/hackathon/datas/01_registro_alumnado_personal/data/ESTANDAR_BASICA_I2324.csv', encoding='latin1')
df_1[['entidad','n_entidad','nivel', 'periodo','insc_t','hom_t','muj_t','egre_hom','egre_muj','egre_tot','docente_h','docente_m','tot_doc']].head()

,entidad,n_entidad,nivel,periodo,insc_t,hom_t,muj_t,egre_hom,egre_muj,egre_tot,docente_h,docente_m,tot_doc
0,1,AGUASCALIENTES,PREESCOLAR,I2324,18,12,6,0,0,0,0,2,2
1,1,AGUASCALIENTES,PREESCOLAR,I2324,90,45,45,0,0,0,0,3,3
2,1,AGUASCALIENTES,PREESCOLAR,I2324,29,17,12,0,0,0,0,2,2
3,1,AGUASCALIENTES,PREESCOLAR,I2324,52,26,26,0,0,0,0,3,3
4,1,AGUASCALIENTES,PREESCOLAR,I2324,22,9,13,0,0,0,0,2,2

In [ ]:
df_1=pd.read_csv('/content/drive/MyDrive/HackODS/elias/hackathon/datas/01_registro_alumnado_personal/data/educacion_basica_2024_2025.csv', encoding='latin1')
df_1[['entidad','n_entidad','nivel', 'periodo','insc_t','hom_t','muj_t','egre_hom','egre_muj','egre_tot','docente_h','docente_m','tot_doc']].head()

,entidad,n_entidad,nivel,periodo,insc_t,hom_t,muj_t,egre_hom,egre_muj,egre_tot,docente_h,docente_m,tot_doc
0,1,Aguascalientes,Secundaria,I2425,37,22,15,6,5,11,1,1,2
1,1,Aguascalientes,Primaria,I2425,146,71,75,0,0,0,2,4,6
2,1,Aguascalientes,Preescolar,I2425,11,5,6,0,0,0,0,1,1
3,1,Aguascalientes,Primaria,I2425,146,65,81,0,0,0,3,3,6
4,1,Aguascalientes,Primaria,I2425,468,240,228,0,0,0,0,12,12

In [ ]:
df_2=pd.read_csv('/content/drive/MyDrive/HackODS/elias/hackathon/datas/01_registro_alumnado_personal/data/media_superior_2019-2020.csv', encoding='latin1')
#df_1[['entidad','n_entidad','nivel', 'periodo','insc_t','hom_t','muj_t','egre_hom','egre_muj','egre_tot','docente_h','docente_m','tot_doc']].head()
df_2[['entidad','c_nom_ent','nivel','alumnos','hombres','mujeres','egresados_h','egresados_m','egresados','docentes_h','docentes_m','docentes']].head()

,entidad,c_nom_ent,nivel,alumnos,hombres,mujeres,egresados_h,egresados_m,egresados,docentes_h,docentes_m,docentes
0,1,AGUASCALIENTES,MEDIA SUPERIOR,353,181,172,22,41,63,8,10,18
1,1,AGUASCALIENTES,MEDIA SUPERIOR,328,176,152,21,29,50,6,9,15
2,1,AGUASCALIENTES,MEDIA SUPERIOR,434,147,287,44,95,139,6,19,25
3,1,AGUASCALIENTES,MEDIA SUPERIOR,407,160,247,49,80,129,7,13,20
4,1,AGUASCALIENTES,MEDIA SUPERIOR,605,231,374,74,121,195,10,13,23

In [ ]:
df_2=pd.read_csv('/content/drive/MyDrive/HackODS/elias/hackathon/datas/01_registro_alumnado_personal/data/educacion_media_superior_2024_2025.csv', encoding='latin1')
df_2[['entidad','c_nom_ent','nivel','alumnos','hombres','mujeres','egresados_h','egresados_m','egresados','docentes_h','docentes_m','docentes']].head()

,entidad,c_nom_ent,nivel,alumnos,hombres,mujeres,egresados_h,egresados_m,egresados,docentes_h,docentes_m,docentes
0,1,Aguascalientes,Media Superior,309,133,176,24,35,59,4,8,12
1,1,Aguascalientes,Media Superior,332,166,166,25,46,71,7,10,17
2,1,Aguascalientes,Media Superior,438,156,282,49,88,137,6,16,22
3,1,Aguascalientes,Media Superior,417,155,262,30,68,98,10,11,21
4,1,Aguascalientes,Media Superior,639,264,375,81,96,177,0,4,4

## Empezar dash

In [3]:
# Define the path to your folder containing CSV files
folder_path = '/content/drive/MyDrive/HackODS/elias/hackathon/datas/01_registro_alumnado_personal/data/basica_y_nms/' # <-- IMPORTANT: Replace with your actual folder path

# Create an empty list to store individual DataFrames
df_list = []

# Check if the folder exists
if not os.path.isdir(folder_path):
    print(f"Error: The folder '{9}' was not found. Please ensure the path is correct.")
else:
    # Iterate over all files in the specified folder
    for filename in os.listdir(folder_path):
        if filename.endswith('.csv'):
            file_path = os.path.join(folder_path, filename)
            print(f"Reading {file_path}...")
            try:
                df = pd.read_csv(file_path, encoding='latin1')
                df = df.rename(columns={'n_entidad': 'n_entidad', 'c_nom_ent': 'n_entidad'})
                df = df.rename(columns={'insc_t': 'insc_t', 'alumnos': 'insc_t'})
                df = df.rename(columns={'hom_t': 'hom_t', 'hombres': 'hom_t'})
                df = df.rename(columns={'muj_t': 'muj_t', 'mujeres': 'muj_t'})
                df = df.rename(columns={'egre_hom': 'egre_hom', 'egresados_h': 'egre_hom'})
                df = df.rename(columns={'egre_muj': 'egre_muj', 'egresados_m': 'egre_muj'})
                df = df.rename(columns={'egre_tot': 'egre_tot', 'egresados': 'egre_tot'})
                df = df.rename(columns={'docente_h': 'docente_h', 'docentes_h': 'docente_h'})
                df = df.rename(columns={'docente_m': 'docente_m', 'docentes_m': 'docente_m'})
                df = df.rename(columns={'tot_doc': 'tot_doc', 'docentes': 'tot_doc'})
                df=df[['entidad','n_entidad','nivel','insc_t','hom_t','muj_t','egre_hom','egre_muj','egre_tot','docente_h','docente_m','tot_doc']]#pd.read_csv(file_path, encoding='latin1')

                df['nivel'] =df['nivel'].str.strip().str.lower()
                df['n_entidad'] =df['n_entidad'].str.strip().str.lower()
                df['n_entidad'] ="".join(caracter for caracter in df['n_entidad'] if caracter.isalnum())
                df=df.groupby(['entidad','n_entidad','nivel'], as_index=False).sum()

                df_list.append(df)
            except Exception as e:
                print(f"Error reading {filename}: {e}")

    if df_list:
        # Concatenate all DataFrames in the list into a single DataFrame
        combined_df = pd.concat(df_list, ignore_index=True)
        print("\nAll CSV files combined successfully. First 5 rows of the combined DataFrame:")
        print(combined_df.head())
    else:
        print("No CSV files found in the specified folder or an error occurred during reading.")

Reading /content/drive/MyDrive/HackODS/elias/hackathon/datas/01_registro_alumnado_personal/data/basica_y_nms/Copia de BASICA_2021-2022.csv...
Reading /content/drive/MyDrive/HackODS/elias/hackathon/datas/01_registro_alumnado_personal/data/basica_y_nms/Copia de BASICA_2020-2021.csv...
Reading /content/drive/MyDrive/HackODS/elias/hackathon/datas/01_registro_alumnado_personal/data/basica_y_nms/Copia de BASICA_2019-2020.csv...
Reading /content/drive/MyDrive/HackODS/elias/hackathon/datas/01_registro_alumnado_personal/data/basica_y_nms/Copia de BASICA_2022-2023.csv...
Reading /content/drive/MyDrive/HackODS/elias/hackathon/datas/01_registro_alumnado_personal/data/basica_y_nms/Copia de ESTANDAR_BASICA_I2324.csv...
Reading /content/drive/MyDrive/HackODS/elias/hackathon/datas/01_registro_alumnado_personal/data/basica_y_nms/Copia de media_superior_2019-2020.csv...
Reading /content/drive/MyDrive/HackODS/elias/hackathon/datas/01_registro_alumnado_personal/data/basica_y_nms/Copia de media_superior_2020-2021.csv...
Reading /content/drive/MyDrive/HackODS/elias/hackathon/datas/01_registro_alumnado_personal/data/basica_y_nms/Copia de educacion_basica_2024_2025.csv...
Reading /content/drive/MyDrive/HackODS/elias/hackathon/datas/01_registro_alumnado_personal/data/basica_y_nms/Copia de media_superior_2021-2022.csv...
Reading /content/drive/MyDrive/HackODS/elias/hackathon/datas/01_registro_alumnado_personal/data/basica_y_nms/Copia de media_superior_2022-2023.csv...
Reading /content/drive/MyDrive/HackODS/elias/hackathon/datas/01_registro_alumnado_personal/data/basica_y_nms/Copia de media_superior_2023-2024.csv...
Reading /content/drive/MyDrive/HackODS/elias/hackathon/datas/01_registro_alumnado_personal/data/basica_y_nms/Copia de educacion_media_superior_2024_2025.csv...

All CSV files combined successfully. First 5 rows of the combined DataFrame:
   entidad                                          n_entidad       nivel  \
0        1  aguascalientesaguascalientesaguascalientesagua...     inicial
1        1  aguascalientesaguascalientesaguascalientesagua...  preescolar
2        1  aguascalientesaguascalientesaguascalientesagua...    primaria
3        1  aguascalientesaguascalientesaguascalientesagua...  secundaria
4        2  aguascalientesaguascalientesaguascalientesagua...     inicial

   insc_t  hom_t  muj_t  egre_hom  egre_muj  egre_tot  docente_h  docente_m  \
0    3688   1955   1733         0         0         0          1        149
1   51932  26067  25865         0         0         0         30       2067
2  159517  81167  78350         0         0         0       1023       3838
3   74567  37462  37105     11472     11613     23085       1497       2046
4    6850   3626   3224         0         0         0          0        142

   tot_doc
0      150
1     2097
2     4861
3     3543
4      142

In [4]:
# 2. Leer y concatenar todos los archivos
df_final = pd.concat(df_list, ignore_index=True)

In [9]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 961 entries, 0 to 960
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   entidad    961 non-null    int64
 1   n_entidad  961 non-null    object
 2   nivel      961 non-null    object
 3   insc_t     961 non-null    int64
 4   hom_t      961 non-null    int64
 5   muj_t      961 non-null    int64
 6   egre_hom   961 non-null    int64
 7   egre_muj   961 non-null    int64
 8   egre_tot   961 non-null    int64
 9   docente_h  961 non-null    int64
 10  docente_m  961 non-null    int64
 11  tot_doc    961 non-null    int64
dtypes: int64(10), object(2)
memory usage: 90.2+ KB

In [15]:
df_final=df_final.groupby(['entidad','nivel'], as_index=False).sum()

In [23]:
df_final=df_final[['entidad','nivel','insc_t','hom_t','muj_t','egre_hom','egre_muj','egre_tot','docente_h','docente_m','tot_doc']]#pd.read_csv(file_path, encoding='latin1')

In [36]:
df_final['porc_aban_hom'] = np.where(df_final['hom_t'] == 0, 0, 1 - df_final['egre_hom'] / df_final['hom_t'])
df_final['porc_aban_muj'] = np.where(df_final['muj_t'] == 0, 0, 1 - df_final['egre_muj'] / df_final['muj_t'])
df_final['porc_aban_tot'] = np.where(df_final['insc_t'] == 0, 0, 1 - df_final['egre_tot'] / df_final['insc_t'])
df_final['porc_doc_hom'] = np.where(df_final['tot_doc'] == 0, 0, df_final['docente_h'] / df_final['tot_doc'])
df_final['porc_doc_muj'] = np.where(df_final['tot_doc'] == 0, 0, df_final['docente_m'] / df_final['tot_doc'])
df_final['porc_ins_hom'] = np.where(df_final['insc_t'] == 0, 0, df_final['hom_t'] / df_final['insc_t'])
df_final['porc_insc_muj'] = np.where(df_final['insc_t'] == 0, 0, df_final['muj_t'] / df_final['insc_t'])
df_final

,entidad,nivel,insc_t,hom_t,muj_t,egre_hom,egre_muj,egre_tot,docente_h,docente_m,tot_doc,porc_aban_hom,porc_aban_muj,porc_aban_tot,porc_doc_hom,porc_doc_muj,porc_ins_hom,porc_insc_muj
0,1,inicial,24641,12925,11716,0,0,0,8,1039,1047,1.000000,1.000000,1.000000,0.007641,0.992359,0.524532,0.475468
1,1,media superior,356395,170332,186063,47618,55189,102807,17344,18382,35726,0.720440,0.703385,0.711536,0.485473,0.514527,0.477930,0.522070
2,1,preescolar,313751,158070,155681,0,0,0,91,12573,12664,1.000000,1.000000,1.000000,0.007186,0.992814,0.503807,0.496193
3,1,primaria,958697,487085,471612,0,0,0,6051,23448,29499,1.000000,1.000000,1.000000,0.205126,0.794874,0.508070,0.491930
4,1,secundaria,446286,224897,221389,64575,67510,132085,9102,12482,21584,0.712869,0.695062,0.704035,0.421701,0.578299,0.503930,0.496070
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,32,inicial,26409,13508,12901,0,0,0,0,870,870,1.000000,1.000000,1.000000,0.000000,1.000000,0.511492,0.488508
156,32,media superior,389825,180959,208866,43815,57137,100952,15775,14183,29958,0.757873,0.726442,0.741033,0.526571,0.473429,0.464206,0.535794
157,32,preescolar,420715,211539,209176,0,0,0,1192,15258,16450,1.000000,1.000000,1.000000,0.072462,0.927538,0.502808,0.497192
158,32,primaria,1159547,586871,572676,0,0,0,18823,26454,45277,1.000000,1.000000,1.000000,0.415730,0.584270,0.506121,0.493879
159,32,secundaria,530833,266496,264337,75677,79822,155499,9342,11560,20902,0.716030,0.698029,0.707066,0.446943,0.553057,0.502034,0.497966

In [48]:
df_1=pd.read_csv('/content/drive/MyDrive/HackODS/elias/hackathon/datas/01_registro_alumnado_personal/data/BASICA_2021-2022.csv', encoding='utf8')
df_1=df_1[['entidad','n_entidad']].drop_duplicates()

df_1['n_entidad'] =df_1['n_entidad'].str.strip().str.lower()
df_1['n_entidad']=df_1['n_entidad'].str.replace(r'[^a-zA-Z0-9\s]', '')
df_1

        entidad                        n_entidad
0             1                   aguascalientes
1833          2                  baja california
5637          3              baja california sur
6734          4                         campeche
8701          5             coahuila de zaragoza
13107         6                           colima
14231         7                          chiapas
32801         8                        chihuahua
38840         9                 ciudad de méxico
46517        10                          durango
51862        11                       guanajuato
62379        12                         guerrero
72777        13                          hidalgo
80600        14                          jalisco
93679        15                           méxico
113293       16              michoacán de ocampo
124587       17                          morelos
127759       18                          nayarit
130753       19                       nuevo león
137552       20                           oaxaca
150777       21                           puebla
162884       22                        querétaro
166703       23                     quintana roo
168972       24                  san luis potosí
177126       25                          sinaloa
183103       26                           sonora
187411       27                          tabasco
192524       28                       tamaulipas
198041       29                         tlaxcala
200096       30  veracruz de ignacio de la llave
220585       31                          yucatán
224038       32                        zacatecas

In [59]:
df_final_1=df_final.merge(df_1, on='entidad', how='left')
df_final_1=df_final_1[['entidad','n_entidad',	'nivel','insc_t',	'hom_t','muj_t',	'egre_hom',	'egre_muj',	'egre_tot',
                   'docente_h',	'docente_m',	'tot_doc',	'porc_aban_hom',	'porc_aban_muj',	'porc_aban_tot',
                   'porc_doc_hom',	'porc_doc_muj',	'porc_ins_hom',	'porc_insc_muj']]
df_final_1[:1]

,entidad,n_entidad,nivel,insc_t,hom_t,muj_t,egre_hom,egre_muj,egre_tot,docente_h,docente_m,tot_doc,porc_aban_hom,porc_aban_muj,porc_aban_tot,porc_doc_hom,porc_doc_muj,porc_ins_hom,porc_insc_muj
0,1,aguascalientes,inicial,24641,12925,11716,0,0,0,8,1039,1047,1.0,1.0,1.0,0.007641,0.992359,0.524532,0.475468

In [56]:
df_final_1.to_csv('/content/drive/MyDrive/HackODS/Plata/1_archivo_final.csv', index=False)